apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-app-deployment
  labels:
    app: dev-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev-app
  template:
    metadata:
      labels:
        app: dev-app
    spec:
      containers:
      - name: app
        image: dev-app:latest # Use the image built by Docker Makefile
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dev-app-service
spec:
  selector:
    app: dev-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
